export const data=[
    {  imgUrl:"https://m.media-amazon.com/images/I/A1JOaV3B6fL._AC_SL1500_.jpg",
        title:"Moana ",
        description:"Disney Film",
        bt:"Watch ",
        rate:10,
        id : 1,
        video:"https://www.youtube.com/embed/cPAbx5kgCJo",
        topic:"Moana stands out from the crowd. She is sea-loving, headstrong, strong-willed, practically fearless, and physically capable",
      },
      { imgUrl:"https://lumiere-a.akamaihd.net/v1/images/p_coco_19736_fd5fa537.jpeg?region=0%2C0%2C540%2C810",
        title:"COCO ",
        description:" Disney Film",
        bt:"Watch ",
        rate:9,
        id : 2,
        video:"https://www.youtube.com/embed/yg8116aeD7E",
        topic:"The concept for Coco is inspired by the Mexican holiday Day of the Dead. The film was scripted by Molina and Matthew Aldrich from a story by Unkrich",
      },
       {imgUrl:"https://media.services.cinergy.ch/media/box1600/97e60f91f99241efea976da057a2235a1bd078e1.jpg",
        title:"Encanto",
        description:" Disney Film",
        bt:"Watch",
        rate:8,
        id:3,
        video:"https://www.youtube.com/embed/CaimKeDcudo",
        topic:"Encanto is a 2021 American computer-animated musical fantasy comedy film produced by Walt Disney Animation Studios and distributed by Walt Disney Studios Motion Pictures.",
      },
      { imgUrl:"https://m.media-amazon.com/images/M/MV5BZWNiOTc4NGItNGY4YS00ZGNkLThkOWEtMDE2ODcxODEwNjkwXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
        title:"Raya and The Last Dragon",
        description:" Disney Film",
        bt:"Watch ",
        rate:3,
        id:4,
        video:"https://www.youtube.com/embed/1VIZ89FEjYI",
        topic:"Raya and the Last Dragon is about the titular warrior princess, Raya. She seeks out the fabled last dragon, hoping to restore the dragon gem that would bring back her father and banish the evil spirits known as the Druun from the land of Kumandra.",
      },
      { imgUrl:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjSvnJc2ChhO9Y6LsuBKeLmzPw8zekDqEB2w&usqp=CAU",
        title:"Dragon Ball",
        description:" Disney Film",
        bt:"Watch",
        rate:2,
        id:5,
        video:"https://www.youtube.com/embed/xs-t6lGMdXU",
        topic:"The series begins with a young monkey-tailed boy named Goku befriending a teenage girl named Bulma",
      },
     {
        imgUrl:"https://i0.wp.com/juiceenews.com/wp-content/uploads/2020/04/frozen-3-trois-films-de-plus-une-petite-amie-pour-elsa-dans-la-prochaine-partie-date-de-sortie.jpg?fit=780%2C439&ssl=1",
        title:"Frozen",
        description:" Disney Film",
        bt:"Watch ",
        rate:10,
        id:6,
        video:"https://www.youtube.com/embed/L0MK7qz13bU",
        topic:"The film depicts a princess who sets off on a journey alongside an iceman, his reindeer, and a snowman to find her estranged sister, whose icy powers have inadvertently trapped their kingdom in eternal winter.",
      },
]